### ISSUE TITLE
Animation Issue

### ISSUE THREAD

**Issue by AbdulRehmanWarraich** [fxm90/GradientProgressBar#1]
I am trying to animate progressBar using below code 
"self.progressView.setProgress(0.75, animated: true)"
but progressBar is not animating.

**Comment by fxm90** [comment]
Could you please provide device and iOS-Version information?
Also make sure you are calling "setProgress()" on the main thread.

**Comment by AbdulRehmanWarraich** [comment]
Yes I am doing it on main thread
Device:  iPhone 5
iOS 10.3.1
can we add any custom animation layer ?
Thanks for your response.

**Comment by fxm90** [comment]
Unfortunately I can't reproduce the bug in the simulator..
Maybe you can try wrapping your call in an CATransaction like this:
```swift
        CATransaction.begin()
        CATransaction.setAnimationDuration(2.0) // Change to whatever you need
        
        progressView.setProgress(progress, animated: true)
        
        CATransaction.commit()
```

**Comment by AbdulRehmanWarraich** [comment]
is there any way to add custom animation on CAGradientLayer. I tried some examples so far but no luck. Can you help me with this. Thanks 👍

**Comment by fxm90** [comment]
But the issue regarding the basic progress animation is fixed?
I can try ¯\_(ツ)_/¯ So what are you trying to achieve?

**Comment by AbdulRehmanWarraich** [comment]
I just need to increase animation duration to desired value. Thanks for your help.

**Comment by fxm90** [comment]
Okay then the above code should work 🤔

Could you please try updating to version 1.0.1 by running 
```swift
pod update
```
I've removed some code from "layoutSubviews()" so it might work..

You could also try adding ```CATransaction.setDisableActions(false)``` to the code I've posted above.

**Comment by fxm90** [comment]
Is this issue still outstanding?
