### ISSUE TITLE
init(dynamicProvider:)' is only available in tvOS 13.0 or newer

### ISSUE THREAD

**Issue by shahbazsaleem01** [fxm90/GradientProgressBar#10]
I'm getting error for availability of API. Error is in an extension.
I'm using swift package manager and i'm on latest version of library which is 2.0.3.

<img width="1066" alt="Screenshot 2020-03-13 at 1 36 01 PM" src="https://user-images.githubusercontent.com/27302852/76604040-d0d96d80-652f-11ea-9e2a-6aea105ef662.png">

**Comment by shahbazsaleem01** [comment]
I don't know from where the tvOS comes from; my app only for iOS.

**Comment by fxm90** [comment]
I just created a clean project, added `GradientLoadingBar` via Swift PM, and it compiled without any errors. Having a `tvOS` related error message is indeed very strange 🤔 Have you tried the "typical" tricks, like deleting derived data and run a clean build?

**Comment by shahbazsaleem01** [comment]
Restarting mac worked for me... now i have no errors... lolzz
