### ISSUE TITLE
cornerRadius for the layers does not work

### ISSUE THREAD

**Issue by murad1981** [fxm90/GradientProgressBar#2]
setting the cornerRadius property for both layers: the gradient layer and mask layer has no effect, is there a way to change the corner radius for them so that (for example) the edges of the progress appear rounded ?

**Comment by fxm90** [comment]
I've just tried 
```
    override func viewDidLoad() {
        super.viewDidLoad()

        gradientProgressBar.layer.cornerRadius = 8.0
        gradientProgressBar.layer.masksToBounds = true
    }
```
in the example application and it seems to work. Maybe you're missing `masksToBounds` ?

**Comment by murad1981** [comment]
ok it sounds there is some problem with my XCode, I've applied the code you posted, it affects only the track bar but not the progress bar itself 
<img width="244" alt="screen shot 2018-10-28 at 12 49 07 pm" src="https://user-images.githubusercontent.com/1199045/47614359-e15e8480-daaf-11e8-8677-738fae0e1dd2.png">

**Comment by fxm90** [comment]
Is your `cornerRadius` maybe greater than your progress-bar height?

This is how it looks in my simulator with **`height: 16.0`**, **`cornerRadius: 8.0`**:
![simulator screen shot - iphone xr - 2018-10-28 at 11 38 51](https://user-images.githubusercontent.com/17249312/47614821-254c8c00-daa6-11e8-9563-0be7b9121556.png)

This is how it looks in my simulator with **`height: 8.0`**, **`cornerRadius: 4.0`**:
![simulator screen shot - iphone xr - 2018-10-28 at 11 37 58](https://user-images.githubusercontent.com/17249312/47614822-254c8c00-daa6-11e8-85b0-a4e97ccaae0e.png)

**Comment by fxm90** [comment]
@murad1981 Can I close this issue?
